FROM pytorch/pytorch:2.4.0-cuda12.1-cudnn9-runtime
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

ENV UV_CACHE_DIR=/app/.cache
ENV COMPILE_ALL=true
ENV SURYA_DETECTION_FOLDER=/app/.cache/surya/detection
ENV SURYA_RECOGNITION_FOLDER=/app/.cache/surya/recognition

COPY pyproject.toml /app/pyproject.toml
COPY uv.lock /app/uv.lock

RUN uv sync --no-cache --group ocr-service

ENV PYTHONPATH=/app
COPY ocr_service /app/ocr_service
COPY src /app/src
RUN uv run /app/ocr_service/utils/download.py
ENV PATH=$PATH:/app/.venv/bin/
CMD ["uv", "run", "ocr_service/main.py"]
