FROM python:3.10-slim AS paddle_model
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

RUN apt update -qy && apt install -qy ffmpeg libsm6 libxext6 curl poppler-utils && apt autoremove
ENV UV_CACHE_DIR=/app/.cache
ENV PADDLE_OCR_BASE_DIR=/app/.cache/paddle/

COPY benchmark/paddle/2.10.0/pyproject.toml  /app/
RUN uv sync
ENV PYTHONPATH=/app
COPY ocr_service /app/ocr_service
COPY src /app/src
RUN uv run /app/ocr_service/utils/download_paddle_models.2.10.0.py --version PP-OCRv4 --folder $PADDLE_OCR_BASE_DIR
ENV PATH=$PATH:/app/.venv/bin/
