FROM paddlepaddle/paddle:3.0.0 AS paddle_model
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update -qy && \
    apt-get install -qy --no-install-recommends \
    ffmpeg \
    libsm6 \
    libxext6 \
    libgl1 \
    libglib2.0-0 \
    poppler-utils \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV MKLDNN_VERBOSE=1
ENV UV_CACHE_DIR=/app/.cache
ENV PADDLE_OCR_BASE_DIR=/app/.cache/paddle/
ENV PADDLE_PDX_CACHE_HOME=/app/.tmp/paddlex/
ARG PADDLE_OCR_VERSION="PP-OCRv3"
ENV PADDLE_OCR_VERSION=${PADDLE_OCR_VERSION}

WORKDIR /app

COPY pyproject.toml uv.lock /app/

RUN uv sync --no-cache --group ocr-service-paddle

ENV PYTHONPATH=/app
COPY ocr_service /app/ocr_service
COPY src /app/src
RUN uv run /app/ocr_service/utils/download_paddle_models.py
ENV PATH=$PATH:/app/.venv/bin/
CMD ["uv", "run", "ocr_service/main.py"]

FROM paddle_model AS test
RUN uv sync --group test --group ocr-service-paddle
COPY tests /app/tests
CMD ["uv", "run", "ocr_service/main.py"]
