FROM python:3.10-slim AS paddle_model
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/
ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

RUN apt update -qy && apt install -qy ffmpeg libsm6 libxext6 curl poppler-utils && apt autoremove
ENV UV_CACHE_DIR=/app/.cache
ENV PADDLE_OCR_BASE_DIR=/app/.cache/paddle/

COPY pyproject.toml /app/pyproject.toml
COPY uv.lock /app/uv.lock

RUN uv sync --no-cache --group ocr-service-paddle

ENV PYTHONPATH=/app
COPY ocr_service /app/ocr_service
COPY src /app/src
RUN uv run /app/ocr_service/utils/download_paddle_models.py --version PP-OCRv4 --folder $PADDLE_OCR_BASE_DIR
ENV PATH=$PATH:/app/.venv/bin/
CMD ["uv", "run", "ocr_service/main.py"]

FROM paddle_model AS test
RUN uv sync --group test --group ocr-service-paddle
COPY tests /app/tests
CMD ["uv", "run", "ocr_service/main.py"]
