include:
  - project: $CATALOG_PATH
    file: vault-ci.yml
    ref: main
  - project: $CATALOG_PATH
    file: kaniko-ci.yml
    ref: main

default:
  image: alpine:latest

variables:
  TAG: "${CI_COMMIT_REF_SLUG}"
  REGISTRY_URL: "${REGISTRY_HOST}/${PROJECT_PATH}"

stages:
  - read-secret
  - docker-build

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

docker-build:
  variables:
    # WORKING_DIR: "frontend"
    IMAGE_NAMES: ocr-api:${CI_COMMIT_REF_SLUG} ocr-api:${CI_COMMIT_SHORT_SHA} ocr-api:${CI_COMMIT_TAG}
    DOCKERFILE: "Dockerfile"
    # BUILD_ARGS: --build-arg=VERSION=1.1.1
  stage: docker-build
  extends:
    - .kaniko:build-push