include:
  - project: $CATALOG_PATH
    file: vault-ci.yml
    ref: main
  - project: $CATALOG_PATH
    file: kaniko-ci.yml
    ref: main

default:
  image: alpine:latest

variables:
  TAG: "${CI_COMMIT_REF_SLUG}"
  REGISTRY_URL: "${REGISTRY_HOST}/${PROJECT_PATH}"

stages:
  - read-secret
  - docker-build

read_secret:
  stage: read-secret
  extends:
    - .vault:read_secret

docker-build-ocr-api:
  variables:
    IMAGE_NAMES: ocr-api:${CI_COMMIT_REF_SLUG} ocr-api:${CI_COMMIT_SHORT_SHA} ocr-api:${CI_COMMIT_TAG}
    DOCKERFILE: "apps/server/ocr_backend/Dockerfile"
  stage: docker-build
  extends:
    - .kaniko:build-push

docker-build-ocr-service-paddle-2.10.0:
  variables:
    IMAGE_NAMES: ocr-service-paddle-2.10.0:${CI_COMMIT_REF_SLUG} ocr-service-paddle:${CI_COMMIT_SHORT_SHA} ocr-service-paddle:${CI_COMMIT_TAG}
    DOCKERFILE: "apps/server/business/paddleocr2/Dockerfile"
  stage: docker-build
  extends:
    - .kaniko:build-push

# docker-build-ocr-service-paddle-2.10.0-gpu:
#   variables:
#     IMAGE_NAMES: ocr-service-paddle-gpu:${CI_COMMIT_REF_SLUG} ocr-service-paddle-gpu:${CI_COMMIT_SHORT_SHA} ocr-service-paddle-gpu:${CI_COMMIT_TAG}
#     DOCKERFILE: "apps/server/business/paddleocr2/Dockerfile.gpu"
#   stage: docker-build
#   extends:
#     - .kaniko:build-push


docker-build-ocr-service-paddle-3.1.0:
  variables:
    IMAGE_NAMES: ocr-service-paddle-3.1.0:${CI_COMMIT_REF_SLUG} ocr-service-paddle-3.1.0:${CI_COMMIT_SHORT_SHA} ocr-service-paddle-3.1.0:${CI_COMMIT_TAG}
    DOCKERFILE: "apps/server/business/paddleocr3/Dockerfile"
  stage: docker-build
  extends:
    - .kaniko:build-push

# docker-build-ocr-service-paddle-gpu:
#   variables:
#     IMAGE_NAMES: ocr-service-paddle-gpu:${CI_COMMIT_REF_SLUG} ocr-service-paddle-gpu:${CI_COMMIT_SHORT_SHA} ocr-service-paddle-gpu:${CI_COMMIT_TAG}
#     DOCKERFILE: "Dockerfiles/services/paddleocr/3.1.0/Dockerfile.gpu"
#   stage: docker-build
#   extends:
#     - .kaniko:build-push

docker-build-ocr-service-llm:
  variables:
    IMAGE_NAMES: ocr-service-llm:${CI_COMMIT_REF_SLUG} ocr-service-llm:${CI_COMMIT_SHORT_SHA} ocr-service-llm:${CI_COMMIT_TAG}
    DOCKERFILE: "apps/server/business/llm/Dockerfile"
  stage: docker-build
  extends:
    - .kaniko:build-push


docker-build-ocr-flower:
  variables:
    IMAGE_NAMES: ocr-flower:${CI_COMMIT_REF_SLUG} ocr-flower:${CI_COMMIT_SHORT_SHA} ocr-flower:${CI_COMMIT_TAG}
    DOCKERFILE: "apps/server/flower/Dockerfile"
  stage: docker-build
  extends:
    - .kaniko:build-push

docker-build-ocr-frontend:
  variables:
    IMAGE_NAMES: ocr-frontend:${CI_COMMIT_REF_SLUG} ocr-frontend:${CI_COMMIT_SHORT_SHA} ocr-frontend:${CI_COMMIT_TAG}
    DOCKERFILE: "./apps/frontend/Dockerfile"
    WORKING_DIR: "./apps/frontend"
  stage: docker-build
  extends:
    - .kaniko:build-push
