# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: "NAME"-api
  namespace: "PLACEHOLDER_FOR_NAMESPACE"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: "NAME"-api
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: "NAME"-api
      annotations:
        redeploy-hash: "PLACEHOLDER_FOR_IMAGE_HASH"

    spec:
      containers:
      - name: "NAME"-api
        image: "PLACEHOLDER_FOR_IMAGE"
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: registry-secret
      - name: github-regcred
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 10
---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: "NAME"-api-service
spec:
  type: ClusterIP
  selector:
    app: "NAME"-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/affinity: cookie
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/session-cookie-hash: sha1
    nginx.ingress.kubernetes.io/session-cookie-name: route
    # nginx.ingress.kubernetes.io/whitelist-source-range: 127.0.0.0/16,192.168.0.0/16,172.16.0.0/12,10.0.0.0/8,91.121.239.0/28,77.158.219.0/24,92.103.164.0/24,185.24.186.0/24
    # Force HTTPS
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    # Add CORS headers
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, OPTIONS, PUT, DELETE"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
    nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
  name: mirai-"NAME"-api."URL"
spec:
  ingressClassName: public
  rules:
  - host: mirai-"NAME"-api."URL"
    http:
      paths:
      - backend:
          service:
            name: "NAME"-api-service
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - mirai-"NAME"-api."URL"
    secretName: mirai-"NAME"-api."URL"-tls
