services:
  ocr_frontend:
    container_name: ocr_frontend
    restart: always
    working_dir: /app
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    ports:
      - 8081:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules