services:
  ocr_frontend:
    container_name: ocr_frontend
    restart: unless-stopped
    working_dir: /app
    build:
      context: ./apps/client
      dockerfile: Dockerfile
      target: dev
      args:
        PNPM_VERSION: 10.14.0
    environment:
      VITE_SSO_BYPASS: "true"
    ports:
      - "8081:5173"
    volumes:
      - ./apps/client:/app:cached
      - node_modules:/app/node_modules
    tty: true

volumes:
  node_modules:
