services:
  minio:
    image: minio/minio:latest
    container_name: minio_dev
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: server /data
    restart: unless-stopped
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis_dev
    ports:
      - "6379:6379"
    restart: unless-stopped
    env_file:
      - .env

  ocr_service:
    build:
      context: .
      dockerfile: Dockerfiles/ocr_service/Dockerfile
    container_name: ocr_service_dev
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_QUEUE_NAME: redis-queue
      MINIO_BUCKET_NAME: test
      MINIO_END_POINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      DATABASE_URL: sqlite:///./example.db
    depends_on:
      - redis
      - minio

  ocr_backend:
    build:
      context: .
      dockerfile: Dockerfiles/ocr_backend/Dockerfile
    container_name: ocr_backend_dev
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_QUEUE_NAME: redis-queue
      MINIO_BUCKET_NAME: test
      MINIO_END_POINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      DATABASE_URL: sqlite:///./example.db
    depends_on:
      - redis
      - minio

volumes:
  minio_data:
    driver: local
