services:
  ocr_frontend:
    container_name: ocr_frontend
    restart: always
    working_dir: /app
    build:
      context: ./apps/client
      dockerfile: Dockerfile
      target: dev
    env_file:
      - .env
    environment:
      - VITE_SSO_BYPASS=true
    ports:
      - 8081:3000
    volumes:
      - ./apps/client:/app
      - /app/node_modules
