/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppToaster: typeof import('./components/AppToaster.vue')['default']
    CustomCard: typeof import('./components/CustomCard.vue')['default']
    CustomTabs: typeof import('./components/CustomTabs.vue')['default']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrButtonGroup: typeof import('@gouvminint/vue-dsfr')['DsfrButtonGroup']
    DsfrCallout: typeof import('@gouvminint/vue-dsfr')['DsfrCallout']
    DsfrDropdown: typeof import('./components/DsfrDropdown.vue')['default']
    DsfrFileUpload: typeof import('@gouvminint/vue-dsfr')['DsfrFileUpload']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrPagination: typeof import('@gouvminint/vue-dsfr')['DsfrPagination']
    DsfrSearchBar: typeof import('@gouvminint/vue-dsfr')['DsfrSearchBar']
    DsfrTile: typeof import('@gouvminint/vue-dsfr')['DsfrTile']
    InfoBulle: typeof import('./components/InfoBulle.vue')['default']
    MediaResultViewer: typeof import('./components/MediaResultViewer.vue')['default']
    MediaViewer: typeof import('./components/MediaViewer.vue')['default']
    OcrViewer: typeof import('./components/OcrViewer.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    StatModel: typeof import('./components/StatModel.vue')['default']
    TasksTab: typeof import('./components/TasksTab.vue')['default']
    ZoneSelectionModal: typeof import('./components/ZoneSelectionModal.vue')['default']
  }
}
