/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    AppToaster: typeof import('./components/AppToaster.vue')['default']
    BboxDetailPanel: typeof import('./components/BboxDetailPanel.vue')['default']
    BboxDrawingOverlay: typeof import('./components/BboxDrawingOverlay.vue')['default']
    Classification: typeof import('./components/Classification.vue')['default']
    CustomCard: typeof import('./components/CustomCard.vue')['default']
    DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
    DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
    DsfrButtonGroup: typeof import('@gouvminint/vue-dsfr')['DsfrButtonGroup']
    DsfrCallout: typeof import('@gouvminint/vue-dsfr')['DsfrCallout']
    DsfrDropdown: typeof import('./components/DsfrDropdown.vue')['default']
    DsfrFileUpload: typeof import('@gouvminint/vue-dsfr')['DsfrFileUpload']
    DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
    DsfrPagination: typeof import('@gouvminint/vue-dsfr')['DsfrPagination']
    DsfrTile: typeof import('@gouvminint/vue-dsfr')['DsfrTile']
    InfoBulle: typeof import('./components/InfoBulle.vue')['default']
    InfoTooltip: typeof import('./components/InfoTooltip.vue')['default']
    OcrChatbot: typeof import('./components/OcrChatbot.vue')['default']
    OcrImageViewer: typeof import('./components/OcrImageViewer.vue')['default']
    OcrMetricsModal: typeof import('./components/OcrMetricsModal.vue')['default']
    OcrTextModal: typeof import('./components/OcrTextModal.vue')['default']
    OcrTutorial: typeof import('./components/OcrTutorial.vue')['default']
    OcrViewer: typeof import('./components/OcrViewer.vue')['default']
    OcrViewerModal: typeof import('./components/OcrViewerModal.vue')['default']
    PageClassificationPanel: typeof import('./components/PageClassificationPanel.vue')['default']
    ProgressBar: typeof import('./components/ProgressBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./components/SideBar.vue')['default']
    StatModel: typeof import('./components/StatModel.vue')['default']
    StatsModel: typeof import('./components/StatsModel.vue')['default']
    TasksTab: typeof import('./components/TasksTab.vue')['default']
    TokenModal: typeof import('./components/TokenModal.vue')['default']
  }
}

// For TSX support
declare global {
  const AppFooter: typeof import('./components/AppFooter.vue')['default']
  const AppHeader: typeof import('./components/AppHeader.vue')['default']
  const AppToaster: typeof import('./components/AppToaster.vue')['default']
  const BboxDetailPanel: typeof import('./components/BboxDetailPanel.vue')['default']
  const BboxDrawingOverlay: typeof import('./components/BboxDrawingOverlay.vue')['default']
  const Classification: typeof import('./components/Classification.vue')['default']
  const CustomCard: typeof import('./components/CustomCard.vue')['default']
  const DsfrAlert: typeof import('@gouvminint/vue-dsfr')['DsfrAlert']
  const DsfrButton: typeof import('@gouvminint/vue-dsfr')['DsfrButton']
  const DsfrButtonGroup: typeof import('@gouvminint/vue-dsfr')['DsfrButtonGroup']
  const DsfrCallout: typeof import('@gouvminint/vue-dsfr')['DsfrCallout']
  const DsfrDropdown: typeof import('./components/DsfrDropdown.vue')['default']
  const DsfrFileUpload: typeof import('@gouvminint/vue-dsfr')['DsfrFileUpload']
  const DsfrHeader: typeof import('@gouvminint/vue-dsfr')['DsfrHeader']
  const DsfrPagination: typeof import('@gouvminint/vue-dsfr')['DsfrPagination']
  const DsfrTile: typeof import('@gouvminint/vue-dsfr')['DsfrTile']
  const InfoBulle: typeof import('./components/InfoBulle.vue')['default']
  const InfoTooltip: typeof import('./components/InfoTooltip.vue')['default']
  const OcrChatbot: typeof import('./components/OcrChatbot.vue')['default']
  const OcrImageViewer: typeof import('./components/OcrImageViewer.vue')['default']
  const OcrMetricsModal: typeof import('./components/OcrMetricsModal.vue')['default']
  const OcrTextModal: typeof import('./components/OcrTextModal.vue')['default']
  const OcrTutorial: typeof import('./components/OcrTutorial.vue')['default']
  const OcrViewer: typeof import('./components/OcrViewer.vue')['default']
  const OcrViewerModal: typeof import('./components/OcrViewerModal.vue')['default']
  const PageClassificationPanel: typeof import('./components/PageClassificationPanel.vue')['default']
  const ProgressBar: typeof import('./components/ProgressBar.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SideBar: typeof import('./components/SideBar.vue')['default']
  const StatModel: typeof import('./components/StatModel.vue')['default']
  const StatsModel: typeof import('./components/StatsModel.vue')['default']
  const TasksTab: typeof import('./components/TasksTab.vue')['default']
  const TokenModal: typeof import('./components/TokenModal.vue')['default']
}