
# Use ARG in the FROM line and for the uv image stage
ARG DOCKERHUB_MIRROR_URL
FROM ${DOCKERHUB_MIRROR_URL:-docker.io}/nvidia/cuda:11.8.0-devel-ubuntu22.04 AS paddle_model

# Add a build stage for uv image
FROM ghcr.io/astral-sh/uv:latest AS uv_stage

FROM paddle_model AS paddle_model_with_uv
COPY --from=uv_stage /uv /uvx /bin/

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /app

RUN apt update -qy
RUN apt install -qy libsm6 libxext6 curl poppler-utils
RUN apt install -y gcc-9 g++-9
RUN apt install ffmpeg -y
RUN apt autoremove -y
ENV UV_CACHE_DIR=/app/.cache
ENV PADDLE_OCR_BASE_DIR=/app/.cache/paddle/

COPY apps/benchmark/paddle/2.10.0/pyproject.toml  /app/
RUN uv sync
RUN uv add paddlepaddle-gpu==2.6.2
ENV PYTHONPATH=/app
COPY apps/business/__init__.py /app/business/__init__.py
COPY apps/business/paddleocr2 /app/business/paddleocr2
COPY apps/business/cache /app/business/cache
COPY apps/business/checkbox_service /app/business/checkbox_service
RUN uv run /app/business/paddleocr2/utils/download_paddle_models.2.10.0.py --version PP-OCRv4 --folder $PADDLE_OCR_BASE_DIR

COPY apps/src /app/src
COPY apps/services /app/services/

ENV PATH=$PATH:/app/.venv/bin/

FROM paddle_model AS test
RUN uv add pytest pytest-asyncio coverage>=7.8.0 pytest-cov
