"""empty message

Revision ID: bfed94841964
Revises: 
Create Date: 2025-04-30 16:21:03.661699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfed94841964'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('input', sa.JSON(), nullable=True))
    op.add_column('tasks', sa.Column('output', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'output')
    op.drop_column('tasks', 'input')
    # ### end Alembic commands ###
