"""add input output

Revision ID: c8f35b121800
Revises: c6b9baace2a7
Create Date: 2025-05-01 11:24:22.132531

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c8f35b121800"
down_revision: Union[str, None] = "c6b9baace2a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("input", sa.JSON(), nullable=True))
    op.add_column("tasks", sa.Column("output", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "output")
    op.drop_column("tasks", "input")
    # ### end Alembic commands ###
