"""add hash field to tasks

Revision ID: e39e0df5a1a7
Revises: 2de301621b8c
Create Date: 2025-07-15 15:29:47.508103

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e39e0df5a1a7"
down_revision: Union[str, None] = "2de301621b8c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("content_hash", sa.String(), nullable=True))
    op.create_index(op.f("ix_tasks_content_hash"), "tasks", ["content_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_content_hash"), table_name="tasks")
    op.drop_column("tasks", "content_hash")
    # ### end Alembic commands ###
