[project]
name = "ocr-api"

version = "0.10.1"

description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "httpx>=0.28.1",
    "python-json-logger==3.3.0",
    "setuptools>=80.9.0",
    "toml>=0.10.2",
    "minio>=7.2.16",
    "pydantic-settings>=2.10.1",
    "sqlalchemy>=2.0.42",
    "celery[redis]>=5.5.1",
    "flower>=2.0.1",
    "psycopg2-binary>=2.9.10",
    "boto3>=1.40.0",
    "qdrant-client>=1.15.1",
    "aiofiles>=24.1.0",
    "pymupdf>=1.26.3",
]

[dependency-groups]
stress-test = [
    "locust>=2.34.1",
]

test = [
    "httpx>=0.25.0",
    "pytest-asyncio>=0.26.0",
    "pytest==8.3.5",
    "ruff>=0.11.5",
    "pytest-cov>=6.1.1",
    # "celery[pytest]>=5.5.1",
    "pillow>=10.4.0",
    "requests>=2.32.3",
    "coverage>=7.8.0",
    "datasets>=3.6.0",
]
ocr-backend = [
    "httpx>=0.25.0",
    "fastapi>=0.116.1",
    "uvicorn[standard]==0.35.0",
    "python-multipart==0.0.20",
    "prometheus-fastapi-instrumentator>=7.1.0",
    "python-keycloak>=5.7.0",
]

ocr-service-paddle = [
    "opencv-python-headless>=4.11.0.86",
    "paddleocr==2.10.0",
    "paddlepaddle==3.0.0",
    "pdf2image==1.17.0",
    "pillow==10.4.0",
    "psutil>=7.0.0",
    "pynvml>=12.0.0",
]

ocr-service-paddle-gpu = [
    "opencv-python-headless>=4.11.0.86",
    "pdf2image==1.17.0",
    "pillow==10.4.0",
    "psutil>=7.0.0",
    "pynvml>=12.0.0",
]

services = [
    "docx2txt>=0.9",
    "langchain-community>=0.4",
    "langfuse>=3.5.1",
    "odfpy>=1.4.1",
    "opencv-python-headless>=4.11.0.86",
    "pdf2image==1.17.0",
    "pillow==10.4.0",
    "psutil>=7.0.0",
    "pynvml>=12.0.0",
    "pypandoc-binary>=1.15",
    "unstructured>=0.18.15",
]

migration = [
    "alembic>=1.15.2"
]

dev = [
    "ipykernel>=6.29.5",
    "pre-commit>=4.2.0",
    "ruff>=0.12.3",
]

version = [
    "commitizen>=4.6.0",
]
client = [
    "python-magic>=0.4.27",
]
checkbox_service = [
    "boxdetect>=1.0.2",
]
llm = [
    "instructor>=1.5.2",
    "openai>=1.63.2",
    "pydantic>=2.11.5",
]
business-forms = [
    "pillow>=10.4.0",
    "pydantic>=2.11.7",
    "pymupdf>=1.26.3",
]
ocr-service-features = [
    "efficientnet-pytorch>=0.7.1",
    "torch>=2.8.0",
    "torchvision>=0.23.0",
    "transformers>=4.55.2",
]
ocr-docling = [
    "docling>=2.47.1",
]


[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "$version"
version_scheme = "semver"
version_provider = "uv"
update_changelog_on_bump = true
major_version_zero = true



[tool.ruff]
line-length = 120


[tool.uv.sources]
torch = [
    { index = "pytorch-cpu" },
]
torchvision = [
    { index = "pytorch-cpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true
