kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
  - containerPort: 443
    hostPort: 8443
  extraMounts:
  - hostPath: ./ocr-api
    containerPath: /ocr-api
  - hostPath: ./ocr-service
    containerPath: /ocr-service
  - hostPath: ./src
    containerPath: /src
  - containerPath: /var/lib/kubelet/config.json
    hostPath: ~/.docker/config.json
