import { readFileSync } from 'node:fs'
import antfu from '@antfu/eslint-config'
import pluginPlaywright from 'eslint-plugin-playwright'

// `unplugin-auto-import` regenerates this file on every dev/build run and it is
// gitignored, so a fresh clone lints before it ever exists. Read it defensively
// rather than crashing the whole config.
function autoImportGlobals () {
  try {
    const url = new URL('./.eslintrc-auto-import.json', import.meta.url)
    return JSON.parse(readFileSync(url, 'utf-8')).globals ?? {}
  } catch {
    return {}
  }
}

export default antfu(
  {
    vue: true,
    typescript: true,
    jsonc: true,
    yaml: {
      overrides: {
        // `pnpm-workspace.yaml` is rewritten by pnpm itself, and it indents
        // block sequences — do not fight it over two spaces.
        'yaml/indent': 'off',
      },
    },
    ignores: [
      '**/node_modules',
      '**/pnpm-lock.yaml',
      '**/dist/',
      '**/coverage/',
      '**/playwright-report/',
      '**/test-results/',
      '**/public/',
      // Generated by unplugin-auto-import / unplugin-vue-components on every build.
      'src/auto-imports.d.ts',
      'src/components.d.ts',
      '**/*.d.ts',
      '**/.eslintrc-auto-import.json',
      '**/*.md/*.js',
      '**/*.md/*.ts',
    ],
    stylistic: {
      overrides: {
        'style/comma-dangle': ['error', 'always-multiline'],
        'style/quote-props': ['error', 'as-needed', { keywords: false, unnecessary: true }],
        'style/brace-style': ['error', '1tbs', { allowSingleLine: true }],
        'style/max-statements-per-line': ['error', { max: 2 }],
        'style/space-before-function-paren': ['error', 'always'],
        'style/spaced-comment': ['error', 'always', { markers: ['#region', '#endregion', '/'] }],
      },
    },
  },
  {
    name: 'ocr/globals',
    languageOptions: {
      globals: autoImportGlobals(),
    },
  },
  {
    name: 'ocr/rules',
    rules: {
      'antfu/if-newline': 'off',
      curly: ['error', 'all'],
      'jsonc/sort-keys': 'off',
      'no-console': ['error', { allow: ['warn', 'error'] }],
      // The UI is written in French, where a no-break space before `?`, `!`,
      // `:` and `»` is correct typography. Keep flagging it in code, allow it
      // in the strings and templates that hold user-facing prose.
      'no-irregular-whitespace': ['error', { skipStrings: true, skipTemplates: true }],
      'ts/ban-ts-comment': ['error', { 'ts-ignore': 'allow-with-description' }],
      'unused-imports/no-unused-imports': 'error',
      'unused-imports/no-unused-vars': ['error', {
        vars: 'all',
        varsIgnorePattern: '^_',
        args: 'after-used',
        argsIgnorePattern: '^_',
        caughtErrors: 'all',
        caughtErrorsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
      }],
    },
  },
  {
    name: 'ocr/vue',
    files: ['**/*.vue'],
    rules: {
      'vue/max-attributes-per-line': ['error', { singleline: { max: 1 }, multiline: { max: 1 } }],
      'vue/no-irregular-whitespace': ['error', {
        skipStrings: true,
        skipTemplates: true,
        skipHTMLAttributeValues: true,
        skipHTMLTextContents: true,
      }],
      'vue/no-v-html': 'off',
    },
  },
  {
    // `eslint-plugin-playwright` was already a devDependency but never wired in.
    ...pluginPlaywright.configs['flat/recommended'],
    name: 'ocr/playwright',
    files: ['playwright/**/*.{ts,js}'],
    rules: {
      ...pluginPlaywright.configs['flat/recommended'].rules,
      // `login()` asserts on the landing page before returning, so a test whose
      // whole point is "logging in works" is not assertion-less.
      'playwright/expect-expect': ['warn', { assertFunctionNames: ['login'] }],
    },
  },
  {
    name: 'ocr/config-files',
    files: ['*.config.{ts,js}', 'env.d.ts', 'vitest-setup.ts'],
    rules: {
      'no-console': 'off',
    },
  },
).override('antfu/node/rules', {
  rules: {
    'node/prefer-global/process': ['error', 'always'],
    'node/prefer-global/console': ['error', 'always'],
    'node/prefer-global/buffer': ['error', 'always'],
  },
})
