/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/metrics': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Metrics
     * @description Endpoint that serves Prometheus metrics.
     */
    get: operations['metrics_metrics_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/{task_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Task By Id */
    get: operations['get_task_by_id_tasks__task_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/tasks/{task_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Task By Id User */
    get: operations['get_task_by_id_user_v1_tasks__task_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/tasks/user/{user_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Tasks By User Id */
    get: operations['get_tasks_by_user_id_tasks_user__user_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/tasks/user/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Get Tasks By User */
    get: operations['get_tasks_by_user_v1_tasks_user__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/health': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Perform a Health Check */
    get: operations['get_health_health_get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/jobs/{user_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Upload File */
    post: operations['upload_file_jobs__user_id__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/jobs/': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /** Upload Files */
    post: operations['upload_files_v1_jobs__post']
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/text-task/{task_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Download Text Content */
    get: operations['download_text_content_text_task__task_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/v1/text-task/{task_id}': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /** Download Text Content New */
    get: operations['download_text_content_new_v1_text_task__task_id__get']
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    /** Bbox */
    Bbox: {
      /** X */
      x: number
      /** Y */
      y: number
      /** Width */
      width: number
      /** Height */
      height: number
      /** Confidence */
      confidence: number
      /** Text */
      text: string
    }
    /** Body_upload_file_jobs__user_id__post */
    Body_upload_file_jobs__user_id__post: {
      /**
       * File
       * Format: binary
       */
      file: string
    }
    /** Body_upload_files_v1_jobs__post */
    Body_upload_files_v1_jobs__post: {
      /**
       * File
       * Format: binary
       */
      file: string
    }
    /** Checkbox */
    Checkbox: {
      /** X */
      x: number
      /** Y */
      y: number
      /** Width */
      width: number
      /** Height */
      height: number
      /** Confidence */
      confidence: number
      /** Is Checked */
      is_checked: boolean
    }
    /** FormEntry */
    FormEntry: {
      /**
       * Key
       * @description Nom brut du champ extrait
       */
      key: string
      /**
       * Value
       * @description Valeur brute extraite
       */
      value: string
      /**
       * Corrected Key
       * @description Nom de champ corrigé (typo, casse, orthographe …) de key si besoin
       */
      corrected_key?: string | null
      /**
       * Corrected Value
       * @description Valeur corrigée (typo, casse, format date, nombres, orthographe…) de value si besoin
       */
      corrected_value?: string | null
    }
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components['schemas']['ValidationError'][]
    }
    /** Health */
    Health: {
      /** Name */
      name: string
      /** Version */
      version: string
      /** Up Time */
      up_time: string
      /** Extras */
      extras?: {
        [key: string]: unknown
      } | null
      /** Status */
      status?: string | null
      /** Dependencies */
      dependencies?: components['schemas']['Health'][] | null
    }
    /** InputForm */
    InputForm: {
      /** Storage File Path */
      storage_file_path: string
      /** Raw Filename */
      raw_filename: string
      /** Content Type */
      content_type: string
      /** Ext */
      ext: string
      /** Size */
      size: number
    }
    /** Layout */
    Layout: {
      /**
       * Cls Id
       * @description Class ID, an integer.
       */
      cls_id: number
      /**
       * Label
       * @description Class label, a string.
       */
      label: string
      /**
       * Score
       * @description Confidence score of the bounding box, a float.
       */
      score: number
      /**
       * Coordinate
       * @description Coordinates of the bounding box, a list of floats in the format [xmin, ymin, xmax, ymax]
       */
      coordinate: number[]
      /** Content */
      content?: unknown | null
    }
    /** OCRResult */
    OCRResult: {
      /** Type */
      type: string
      /** Model Name */
      model_name: string
      /** Created At */
      created_at: number
      /** Updated At */
      updated_at: number
      /** Version */
      version: string
      /** Total Pages */
      total_pages: number
      /** Pages */
      pages: components['schemas']['Page'][]
      /** Extras */
      extras?: {
        [key: string]: unknown
      } | null
      /**
       * Text
       * @default
       */
      text: string | null
    }
    /** Page */
    Page: {
      /** Page */
      page: number
      /** Page Url */
      page_url?: string | null
      /**
       * Boxes
       * @description Detections
       */
      boxes?: components['schemas']['Bbox'][]
      /**
       * Layouts
       * @description Layout definition
       */
      layouts?: components['schemas']['Layout'][]
      /**
       * Checkboxes
       * @description Checkbox definition
       */
      checkboxes?: components['schemas']['Checkbox'][]
      /**
       * Form Entries
       * @description Form extraction
       */
      form_entries?: components['schemas']['FormEntry'][]
    }
    /** TaskModel */
    TaskModel: {
      /** Id */
      id: string
      /** User Id */
      user_id: string
      /** Type */
      type: string
      /**
       * Status
       * @default queued
       */
      status: string
      /**
       * Percentage
       * @default 0
       */
      percentage: number | null
      input?: components['schemas']['InputForm'] | null
      output?: components['schemas']['OCRResult'] | null
      /** Created At */
      created_at: number
      /** Updated At */
      updated_at: number
      /** Extras */
      extras?: {
        [key: string]: unknown
      } | null
      /** Position */
      position?: number | null
      /** Content Hash */
      content_hash?: string | null
    }
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[]
      /** Message */
      msg: string
      /** Error Type */
      type: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export interface operations {
  metrics_metrics_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': unknown
        }
      }
    }
  }
  get_task_by_id_tasks__task_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        task_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskModel'] | null
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_task_by_id_user_v1_tasks__task_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        task_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskModel'] | null
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_tasks_by_user_id_tasks_user__user_id__get: {
    parameters: {
      query?: {
        page?: number
        page_size?: number
      }
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskModel'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_tasks_by_user_v1_tasks_user__get: {
    parameters: {
      query?: {
        page?: number
        page_size?: number
      }
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskModel'][]
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  get_health_health_get: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Return health of all dependencies */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['Health']
        }
      }
    }
  }
  upload_file_jobs__user_id__post: {
    parameters: {
      query?: never
      header?: never
      path: {
        user_id: string
      }
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_file_jobs__user_id__post']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskModel']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  upload_files_v1_jobs__post: {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    requestBody: {
      content: {
        'multipart/form-data': components['schemas']['Body_upload_files_v1_jobs__post']
      }
    }
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['TaskModel']
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  download_text_content_text_task__task_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        task_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/plain': string
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
  download_text_content_new_v1_text_task__task_id__get: {
    parameters: {
      query?: never
      header?: never
      path: {
        task_id: string
      }
      cookie?: never
    }
    requestBody?: never
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'text/plain': string
        }
      }
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown
        }
        content: {
          'application/json': components['schemas']['HTTPValidationError']
        }
      }
    }
  }
}
