{{- if .Values.enabled }}
{{- if or .Values.frontend.envCm .Values.global.envCm -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ printf "%s-%s" (include "helper.fullname" .) "frontend" }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "frontend")) | nindent 4 }}
data:
  {{- if .Values.global.envCm -}}
  {{- include "helper.env" .Values.global.envCm | indent 2 }}
  {{- end -}}
  {{- if .Values.frontend.envCm -}}
  {{- include "helper.env" .Values.frontend.envCm | indent 2 }}
  {{- end -}}
{{- end -}}
{{- end }}
