"""Make type as primary key

Revision ID: 2de301621b8c
Revises: a7253a308f09
Create Date: 2025-06-16 09:42:04.385541

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "2de301621b8c"
down_revision: Union[str, None] = "a7253a308f09"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Supprime l'ancienne clé primaire (sur id uniquement)
    op.drop_constraint("tasks_pkey", "tasks", type_="primary")
    # Crée la nouvelle clé primaire composite
    op.create_primary_key("tasks_pkey", "tasks", ["id", "type"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Inverse les opérations
    op.drop_constraint("tasks_pkey", "tasks", type_="primary")
    op.create_primary_key("tasks_pkey", "tasks", ["id"])
    # ### end Alembic commands ###
