"""add parent_id to task

Revision ID: 356f06566bde
Revises: e35956b5d5f2
Create Date: 2026-04-17 18:20:25.354267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '356f06566bde'
down_revision: Union[str, None] = 'e35956b5d5f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('parent_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'parent_id')
    # ### end Alembic commands ###
