"""add annotations table

Revision ID: 564486764bcd
Revises: f0199d270d1c
Create Date: 2026-04-02 18:39:58.309515

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "564486764bcd"
down_revision: Union[str, None] = "f0199d270d1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "annotations",
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("task_id", sa.String(), nullable=True),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("output", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.Column("updated_at", sa.BigInteger(), nullable=True),
        sa.Column("extras", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("content_hash"),
    )
    op.create_index(op.f("ix_annotations_task_id"), "annotations", ["task_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_annotations_task_id"), table_name="annotations")
    op.drop_table("annotations")
    # ### end Alembic commands ###
