"""add OcrChunksTable

Revision ID: 85ed6144852d
Revises: 356f06566bde
Create Date: 2026-04-18 14:23:33.394436

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import src.models.ocr_chunks  # noqa: F401 - needed for the JSONB type in the migration


# revision identifiers, used by Alembic.
revision: str = "85ed6144852d"
down_revision: Union[str, None] = "356f06566bde"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ocr_chunks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("content_hash", sa.String(), nullable=False),
        sa.Column("page_nums", src.models.ocr_chunks._JsonbOrJson(), nullable=False),
        sa.Column("bbox_indices", src.models.ocr_chunks._JsonbOrJson(), nullable=False),
        sa.Column("text", sa.String(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("vector", src.models.ocr_chunks._JsonbOrJson(), nullable=False),
        sa.Column("vector_size", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ocr_chunks_content_hash"), "ocr_chunks", ["content_hash"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ocr_chunks_content_hash"), table_name="ocr_chunks")
    op.drop_table("ocr_chunks")
    # ### end Alembic commands ###
