"""add output_encrypted flag to tasks

Revision ID: 96e7697cfcdb
Revises: f0199d270d1c
Create Date: 2026-08-25 00:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "96e7697cfcdb"
down_revision: Union[str, None] = "f0199d270d1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tasks",
        sa.Column("output_encrypted", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index(op.f("ix_tasks_output_encrypted"), "tasks", ["output_encrypted"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tasks_output_encrypted"), table_name="tasks")
    op.drop_column("tasks", "output_encrypted")
    # ### end Alembic commands ###
