"""add parameters

Revision ID: 9a3cc1ff951a
Revises: e39e0df5a1a7
Create Date: 2025-08-15 08:34:12.062354

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9a3cc1ff951a"
down_revision: Union[str, None] = "e39e0df5a1a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks_stats")
    op.add_column("tasks", sa.Column("parameters", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "parameters")
    op.create_table(
        "tasks_stats",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("type", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("percentage", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
        sa.Column("nb_total_item", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("model_name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("version", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("up_vote", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("down_vote", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_at", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("updated_at", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.Column("extras", postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("tasks_stats_pkey")),
    )
    # ### end Alembic commands ###
