"""add entity names

Revision ID: ad3749ac140f
Revises: b791ea2b8ac7
Create Date: 2026-04-20 14:00:07.713542

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ad3749ac140f"
down_revision: Union[str, None] = "b791ea2b8ac7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("templating", sa.Column("entity_names", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("templating", "entity_names")
    # ### end Alembic commands ###
