"""Add group_id to tasks table

Revision ID: cd886281153d
Revises: e39e0df5a1a7
Create Date: 2025-08-01 10:59:52.916680

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "cd886281153d"
down_revision: Union[str, None] = "e39e0df5a1a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tasks", sa.Column("group_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tasks", "group_id")
    # ### end Alembic commands ###
