"""add token table

Revision ID: e35956b5d5f2
Revises: b2c3d4e5f6a7
Create Date: 2026-04-11 12:12:11.892943

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e35956b5d5f2"
down_revision: Union[str, None] = "b2c3d4e5f6a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tokens",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=False),
        sa.Column("created_at", sa.BigInteger(), nullable=True),
        sa.Column("expired_at", sa.BigInteger(), nullable=True),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("roles", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tokens_token"), "tokens", ["token"], unique=True)
    op.create_index(op.f("ix_tokens_user_id"), "tokens", ["user_id"], unique=False)
    op.drop_index(op.f("ix_ocr_chunks_content_hash"), table_name="ocr_chunks")
    op.drop_table("ocr_chunks")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ocr_chunks",
        sa.Column("id", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("content_hash", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("page_nums", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("bbox_indices", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("text", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("model_name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("vector", postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
        sa.Column("vector_size", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("created_at", sa.BIGINT(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("ocr_chunks_pkey")),
    )
    op.create_index(op.f("ix_ocr_chunks_content_hash"), "ocr_chunks", ["content_hash"], unique=False)
    op.drop_index(op.f("ix_tokens_user_id"), table_name="tokens")
    op.drop_index(op.f("ix_tokens_token"), table_name="tokens")
    op.drop_table("tokens")
    # ### end Alembic commands ###
