"""Add template bboxes

Revision ID: f8470d5029e5
Revises: 124df8e39278
Create Date: 2025-08-03 13:59:00.263345

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f8470d5029e5"
down_revision: Union[str, None] = "124df8e39278"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("templates", sa.Column("interest_zone", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("templates", "interest_zone")
    # ### end Alembic commands ###
