apiVersion: v2
name: ocr
type: application
version: 0.2.0-rc.13
appVersion: "0.20.0-rc.13"
description: A Helm chart to deploy ocr.
# home: https://this-is-tobi.com
deprecated: false
annotations: {}
keywords: []
dependencies:
  - name: redis
    alias: redis
    version: 0.27.9
    repository: oci://registry-1.docker.io/cloudpirates
    condition: redis.enabled
  - name: postgres
    alias: postgres
    version: 0.19.6
    repository: oci://registry-1.docker.io/cloudpirates
    condition: postgres.enabled
  - name: rustfs
    alias: rustfs
    version: 0.10.0
    repository: oci://registry-1.docker.io/cloudpirates
    condition: rustfs.enabled
  - name: cluster
    alias: cnpg
    version: 0.8.1
    repository: https://cloudnative-pg.github.io/charts
    condition: cnpg.enabled
sources:
  - https://github.com/IA-Generative/ocr-api
maintainers: []
# - name: this-is-tobi
#   email: this-is-tobi@proton.me
#   url: https://this-is-tobi.com
