name: ci-cd-ghcr

on:
  push:
    branches:
      - 'main'
      - 'staging'

    # paths:
    #   - 'src/**'
    #   - Dockerfile
    #   - deployment.yaml
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: true

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          #tags: type=semver,pattern={{version}},latest=true

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .  # Build Docker image from the current directory (i.e., the root of the repository)
          push: true   # Push the built Docker image to GitHub Packages
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  deploy:
    needs: publish-docker-image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set dynamic envs based on branch
        id: set-env
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "KUBE_CONFIG_SECRET=${{ secrets.KUBE_CONFIG_MAIN }}" >> $GITHUB_ENV
            echo "K8S_NAMESPACE=ocr" >> $GITHUB_ENV
            echo "URL=mirai-ocr-api.c0.cloud-pi-native.com" >> $GITHUB_ENV
          else
            echo "KUBE_CONFIG_SECRET=${{ secrets.KUBE_CONFIG_STAGING }}" >> $GITHUB_ENV
            echo "K8S_NAMESPACE=ocr-staging" >> $GITHUB_ENV
            echo "URL=mirai-staging-ocr-api.c0.cloud-pi-native.com" >> $GITHUB_ENV
          fi

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBE_CONFIG_SECRET" > $HOME/.kube/config

      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ env.KUBE_CONFIG_SECRET }}

      - name: Update deployment.yaml & deploy
        run: |
          IMAGE_HASH=${{ github.sha }}
          IMAGE="${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main"
          IMAGE_LOWERCASE=$(echo $IMAGE | tr '[:upper:]' '[:lower:]')

          sed -i "s|PLACEHOLDER_FOR_IMAGE_HASH|${IMAGE_HASH}|g" deployment.yaml
          sed -i "s|PLACEHOLDER_FOR_IMAGE|${IMAGE_LOWERCASE}|g" deployment.yaml
          sed -i "s|PLACEHOLDER_FOR_NAMESPACE|${K8S_NAMESPACE}|g" deployment.yaml
          sed -i "s|PLACEHOLDER_FOR_URL|${URL}|g" deployment.yaml
          cat ./deployment.yaml
          kubectl apply -f ./deployment.yaml -n ${K8S_NAMESPACE}
  # test-deployement:
  #   needs: deploy
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Wait for the service to be ready
  #       run: sleep 60

  #     - name: Test Service Availability
  #       run: |
  #         URL="http://${{ github.event.repository.name }}.c0.cloud-pi-native.com"
  #         STATUS=$(curl -s -L -o /dev/null -w '%{http_code}' $URL)
  #         if [ $STATUS -ne 200]; then
  #           echo "Service is not running or returned an unexpected error"
  #           exit 1
  #         fi
