name: CI/CD Workflow

on:
  push:
    branches:
      - '**'

jobs:
  run-tests-backend:
    runs-on: actions-runner-controller
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies and run tests
        run: |
          make test-backend-api



  run-tests-service-checkbox:
    runs-on: actions-runner-controller
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies and run tests
        run: |
          make test-services-checkbox

  run-tests-service-paddle:
    runs-on: actions-runner-controller
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies and run tests
        run: |
          make test-services-paddleocr2.10.0
  run-tests-service-paddle3:
    runs-on: actions-runner-controller
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies and run tests
        run: |
          make test-services-paddleocr3.0.1
  # run-tests-service-paddle3-gpu:
  #   runs-on: sdid-app-hp-arc-controller
  #   permissions:
  #     contents: read
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: 3.x

  #     - name: Install dependencies and run tests
  #       run: |
  #         make test-services-paddleocr3.1.0-gpu
